/* 회원 */
CREATE TABLE MEMBER (
	M_NUM NUMBER NOT NULL, /* 회원번호 */
	M_ID VARCHAR2(20), /* 아이디 */
	M_PASS VARCHAR2(20), /* 비밀번호 */
	M_NICK VARCHAR2(40), /* 닉네임 */
	M_EMAIL VARCHAR2(40), /* 이메일 */
	M_NAME VARCHAR2(20), /* 이름 */
	M_TEL NUMBER, /* 전화번호 */
	M_BIRTH DATE, /* 생년월일 */
	M_ADDR VARCHAR(200), /* 주소 */
	M_ADDRD VARCHAR2(200), /* 상세주소 */
	REG_DATE DATE, /* 가입일 */
	M_PHOTO VARCHAR2(50), /* 사진 */
	DEL CHAR DEFAULT 'n', /* 회원삭제 */
	ADMIN CHAR /* 관리자 */
);
ALTER TABLE MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			M_NUM
		);

/* 여행 게시판 */
CREATE TABLE TRIP (
	T_NUM NUMBER NOT NULL, /* 글번호 */
	T_TITLE VARCHAR2(100), /* 제목 */
	T_CONTENT VARCHAR2(3000), /* 내용 */
	REG_DATE DATE, /* 작성일 */
	T_VIEW NUMBER, /* 조회수 */
	T_PHOTO VARCHAR2(50), /* 사진 */
	DEL CHAR DEFAULT 'n', /* 여행글 삭제 */
	M_NUM NUMBER /* 회원번호 */
);
ALTER TABLE TRIP
	ADD
		CONSTRAINT PK_TRIP
		PRIMARY KEY (
			T_NUM
		);
ALTER TABLE TRIP
	ADD
		CONSTRAINT FK_MEMBER_TO_TRIP
		FOREIGN KEY (
			M_NUM
		)
		REFERENCES MEMBER (
			M_NUM
		);

/* 여행 게시판 댓글 */
CREATE TABLE TRIP_REPLY (
	TRE_NUM NUMBER NOT NULL, /* 댓글 번호 */
	TRE_CONTENT VARCHAR2(1000), /* 댓글 내용 */
	REG_DATE DATE, /* 작성일 */
	DEL CHAR DEFAULT 'n', /* 댓글삭제 */
	TRE_REF NUMBER, /* 참조번호 */
	TRE_RE_STEP NUMBER, /* 답글순서 */
	TRE_RE_LEVEL NUMBER, /* 들여쓰기 레벨 */
	T_NUM NUMBER, /* 글번호 */
	M_NUM NUMBER /* 회원번호 */
);
ALTER TABLE TRIP_REPLY
	ADD
		CONSTRAINT PK_TRIP_REPLY
		PRIMARY KEY (
			TRE_NUM
		);

ALTER TABLE TRIP_REPLY
	ADD
		CONSTRAINT FK_TRIP_TO_TRIP_REPLY
		FOREIGN KEY (
			T_NUM
		)
		REFERENCES TRIP (
			T_NUM
		);

ALTER TABLE TRIP_REPLY
	ADD
		CONSTRAINT FK_MEMBER_TO_TRIP_REPLY
		FOREIGN KEY (
			M_NUM
		)
		REFERENCES MEMBER (
			M_NUM
		);

/* 여행 게시판 사진 */
CREATE TABLE TIRP_PHOTO (
	TP_NUM NUMBER NOT NULL, /* 번호 */
	FILENAME VARCHAR2(200), /* 파일명 */
	T_NUM NUMBER /* 글번호 */
);
ALTER TABLE TIRP_PHOTO
	ADD
		CONSTRAINT PK_TIRP_PHOTO
		PRIMARY KEY (
			TP_NUM
		);

ALTER TABLE TIRP_PHOTO
	ADD
		CONSTRAINT FK_TRIP_TO_TIRP_PHOTO
		FOREIGN KEY (
			T_NUM
		)
		REFERENCES TRIP (
			T_NUM
		);

/* 공지사항 */
CREATE TABLE NOTICE (
	NO_NUM NUMBER NOT NULL, /* 글번호 */
	NO_TITLE VARCHAR2(100), /* 제목 */
	NO_CONTENT VARCHAR2(2000), /* 내용 */
	REG_DATE DATE, /* 작성일 */
	NO_VIEW NUMBER, /* 조회수 */
	DEL CHAR DEFAULT 'n', /* 공지사항 삭제 */
	M_NUM NUMBER /* 회원번호 */
);
ALTER TABLE NOTICE
	ADD
		CONSTRAINT PK_NOTICE
		PRIMARY KEY (
			NO_NUM
		);

ALTER TABLE NOTICE
	ADD
		CONSTRAINT FK_MEMBER_TO_NOTICE
		FOREIGN KEY (
			M_NUM
		)
		REFERENCES MEMBER (
			M_NUM
		);

/* 공지사항 댓글 */
CREATE TABLE NOTICE_REPLY (
	NOR_NUM NUMBER NOT NULL, /* 댓글 번호 */
	NOR_CONTENT VARCHAR2(1000), /* 댓글내용 */
	REG_DATE DATE, /* 작성일 */
	DEL CHAR DEFAULT 'n', /* 댓글 삭제 */
	NOR_REF NUMBER, /* 참조번호 */
	NOR_RE_STEP NUMBER, /* 댓글순서 */
	NOR_RE_LEVEL NUMBER, /* 들여쓰기 레벨 */
	M_NUM NUMBER, /* 회원번호 */
	NO_NUM NUMBER /* 글번호 */
);
ALTER TABLE NOTICE_REPLY
	ADD
		CONSTRAINT PK_NOTICE_REPLY
		PRIMARY KEY (
			NOR_NUM
		);

ALTER TABLE NOTICE_REPLY
	ADD
		CONSTRAINT FK_MEMBER_TO_NOTICE_REPLY
		FOREIGN KEY (
			M_NUM
		)
		REFERENCES MEMBER (
			M_NUM
		);

ALTER TABLE NOTICE_REPLY
	ADD
		CONSTRAINT FK_NOTICE_TO_NOTICE_REPLY
		FOREIGN KEY (
			NO_NUM
		)
		REFERENCES NOTICE (
			NO_NUM
		);
/* 스케줄 내역 */
CREATE TABLE SCHEDULE (
	SCH_NUM NUMBER NOT NULL, /* 스케줄 번호 */
	SCH_NAME VARCHAR2(200), /* 스케줄명 */
	S_DATE DATE, /* 여행 시작일자 */
	E_DATE DATE, /* 여행 종료일자 */
	M_NUM NUMBER /* 회원번호 */
);
ALTER TABLE SCHEDULE
	ADD
		CONSTRAINT PK_SCHEDULE
		PRIMARY KEY (
			SCH_NUM
		);

ALTER TABLE SCHEDULE
	ADD
		CONSTRAINT FK_MEMBER_TO_SCHEDULE
		FOREIGN KEY (
			M_NUM
		)
		REFERENCES MEMBER (
			M_NUM
		);

/* 스케줄 상세내역 */
CREATE TABLE SCHEDULE_DETAIL (
	SCHD_NUM NUMBER NOT NULL, /* 스케줄 상세번호 */
	DAY DATE, /* 일자별 분류 */
	VEHICLE VARCHAR2(20), /* 이동수단 */
	SCH_NUM NUMBER, /* 스케줄 번호 */
	PLACE_NUM NUMBER /* 플레이스 번호 */
);
ALTER TABLE SCHEDULE_DETAIL
	ADD
		CONSTRAINT SCHEDULE_DETAIL
		PRIMARY KEY (
			SCHD_NUM
		);

ALTER TABLE SCHEDULE_DETAIL
	ADD
		CONSTRAINT FK_SCHEDULE_TO_SCHEDULE_DETAIL
		FOREIGN KEY (
			SCH_NUM
		)
		REFERENCES SCHEDULE (
			SCH_NUM
		);

ALTER TABLE SCHEDULE_DETAIL
	ADD
		CONSTRAINT FK_PLACE_TO_SCHEDULE_DETAIL
		FOREIGN KEY (
			PLACE_NUM
		)
		REFERENCES PLACE (
			PLACE_NUM
		);

/* 좋아요 */
CREATE TABLE TRIP_LIKE (
	LIKE_NUM NUMBER NOT NULL, /* 번호 */
	M_NUM NUMBER, /* 회원번호 */
	T_NUM NUMBER /* 글번호 */
);
ALTER TABLE TRIP_LIKE
	ADD
		CONSTRAINT PK_TRIP_LIKE
		PRIMARY KEY (
			LIKE_NUM
		);

ALTER TABLE TRIP_LIKE
	ADD
		CONSTRAINT FK_MEMBER_TO_TRIP_LIKE
		FOREIGN KEY (
			M_NUM
		)
		REFERENCES MEMBER (
			M_NUM
		);

ALTER TABLE TRIP_LIKE
	ADD
		CONSTRAINT FK_TRIP_TO_TRIP_LIKE
		FOREIGN KEY (
			T_NUM
		)
		REFERENCES TRIP (
			T_NUM
		);

/* 고객문의 */
CREATE TABLE CS (
	NUM NUMBER NOT NULL, /* 글번호 */
	CS_TITLE VARCHAR2(100), /* 제목 */
	REG_DATE DATE, /* 작성일 */
	CS_CONTENT VARCHAR2(2000), /* 내용 */
	CS_VIEW NUMBER, /* 조회수 */
	CS_REF NUMBER, /* 참조번호 */
	CS_RE_STEP NUMBER, /* 답글순서 */
	CS_RE_LEVEL NUMBER, /* 들여쓰기 레벨 */
	M_NUM NUMBER /* 회원번호 */
);
ALTER TABLE CS
	ADD
		CONSTRAINT PK_CS
		PRIMARY KEY (
			NUM
		);

ALTER TABLE CS
	ADD
		CONSTRAINT FK_MEMBER_TO_CS
		FOREIGN KEY (
			M_NUM
		)
		REFERENCES MEMBER (
			M_NUM
		);
/* 플레이스 */
CREATE TABLE PLACE (
	PLACE_NUM NUMBER NOT NULL, /* 플레이스 번호 */
	PLACE_NAME VARCHAR2(100), /* 명칭 */
	PLACE_CATE VARCHAR2(20), /* 카테고리 */
	PLACE_ADDR VARCHAR2(200), /* 주소 */
	PLACE_ADDRD VARCHAR2(200), /* 상세주소 */
	PLACE_PHOTO VARCHAR2(200), /* 사진 */
	LAT VARCHAR2(30), /* 위도 */
	LNG VARCHAR2(30), /* 경도 */
	REG_DATE DATE /* 등록일자 */
);
ALTER TABLE PLACE
	ADD
		CONSTRAINT PK_PLACE
		PRIMARY KEY (
			PLACE_NUM
		);
        
alter table place add place_content varchar2(2000); 
alter table place add place_area varchar2(20); 

/* 플레이스 후기 */
CREATE TABLE PLACE_REVIEW (
	PREV_NUM NUMBER NOT NULL, /* 후기 번호 */
	PREV_TITLE VARCHAR2(100), /* 제목 */
	SCORE NUMBER, /* 평점 */
	PREV_CONTENT VARCHAR2(2000), /* 내용 */
	DEL CHAR DEFAULT 'n', /* 후기 삭제 */
	REG_DATE DATE, /* 작성일 */
	M_NUM NUMBER, /* 회원번호 */
	PLACE_NUM NUMBER /* 플레이스 번호 */
);
ALTER TABLE PLACE_REVIEW
	ADD
		CONSTRAINT PK_PLACE_REVIEW
		PRIMARY KEY (
			PREV_NUM
		);

ALTER TABLE PLACE_REVIEW
	ADD
		CONSTRAINT FK_MEMBER_TO_PLACE_REVIEW
		FOREIGN KEY (
			M_NUM
		)
		REFERENCES MEMBER (
			M_NUM
		);

ALTER TABLE PLACE_REVIEW
	ADD
		CONSTRAINT FK_PLACE_TO_PLACE_REVIEW
		FOREIGN KEY (
			PLACE_NUM
		)
		REFERENCES PLACE (
			PLACE_NUM
		);

/* 플레이스 즐찾 */
CREATE TABLE BOOKMARK (
	BOOK_NUM NUMBER NOT NULL, /* 즐겨찾기 번호 */
	M_NUM NUMBER, /* 회원번호 */
	PLACE_NUM NUMBER /* 플레이스 번호 */
);
ALTER TABLE BOOKMARK
	ADD
		CONSTRAINT PK_BOOKMARK
		PRIMARY KEY (
			BOOK_NUM
		);

ALTER TABLE BOOKMARK
	ADD
		CONSTRAINT FK_MEMBER_TO_BOOKMARK
		FOREIGN KEY (
			M_NUM
		)
		REFERENCES MEMBER (
			M_NUM
		);

ALTER TABLE BOOKMARK
	ADD
		CONSTRAINT FK_PLACE_TO_BOOKMARK
		FOREIGN KEY (
			PLACE_NUM
		)
		REFERENCES PLACE (
			PLACE_NUM
		);